export const items = [
  {
    id: 1,
    name: "Item 1",
    description: "Description of Item 1",
    price: 100,
    inStock: 10,
    category: "furniture",
  },
  {
    id: 2,
    name: "Item 2",
    description: "Description of Item 2",
    price: 200,
    inStock: 5,
    category: "furniture",
  },
  {
    id: 3,
    name: "Item 3",
    description: "Description of Item 3",
    price: 300,
    inStock: 0,
    category: "furniture",
  },
  {
    id: 4,
    name: "Item 4",
    description: "Description of Item 4",
    price: 400,
    inStock: 2,
    category: "furniture",
  },
  {
    id: 5,
    name: "Item 5",
    description: "Description of Item 5",
    price: 500,
    inStock: 8,
    category: "clothing",
  },
  {
    id: 6,
    name: "Item 6",
    description: "Description of Item 6",
    price: 600,
    inStock: 1,
    category: "clothing",
  },
  {
    id: 7,
    name: "Item 7",
    description: "Description of Item 7",
    price: 700,
    inStock: 3,
    category: "furniture",
  },
  {
    id: 8,
    name: "Item 8",
    description: "Description of Item 8",
    price: 800,
    inStock: 4,
    category: "electronics",
  },
  {
    id: 9,
    name: "Item 9",
    description: "Description of Item 9",
    price: 900,
    inStock: 6,
    category: "electronics",
  },
  {
    id: 10,
    name: "Item 10",
    description: "Description of Item 10",
    price: 1000,
    inStock: 9,
    category: "furniture",
  },
];
