GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "sigurd",
  "password": "passord"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "sigurd",
  "password": "passord1"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "sigurd",
  "password": "passord"
}

###
POST http://localhost:3000/additem
Content-Type: application/json

{
    "item": {
        "name": "item1",
        "price": 100
    }
}