GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "sigurd",
  "password": "passord"
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "admsigurd",
  "password": "passord",
  "role": "admin"
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "admsigurd",
  "password": "passord",
  "role": "admin"
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "admsigurd",
  "password": "passord",
  "role": "adminn"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "sigurd",
  "password": "passord1"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admsigurd",
  "password": "passord"
}

###
POST http://localhost:3000/addmyitem
Content-Type: application/json

{
    "itemId": 1
}

###
POST http://localhost:3000/items
Content-Type: application/json

{
"name": "Item 3",
"description": "Description of Item 1", 
"price": 100,
"inStock": 10
}


###
GET http://localhost:3000/items

###
GET http://localhost:3000/myitems